/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package user.view;

import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Jostin Castro
 */
public class RegisterForm extends javax.swing.JDialog {

    /**
     * Creates new form RegisterForm
     */
    
    private boolean leapYear;
    
    private boolean isComplete;
    private String email;
    private String name;
    private String id;
    private String password;
    private GregorianCalendar bornDate;
    private int phoneNumber;
    
    
    public RegisterForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        configureDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbId = new javax.swing.JLabel();
        lbMail = new javax.swing.JLabel();
        lbPasword = new javax.swing.JLabel();
        lbConfirmPassword = new javax.swing.JLabel();
        lbBornDate = new javax.swing.JLabel();
        spYear = new javax.swing.JSpinner();
        cbMonth = new javax.swing.JComboBox<>();
        spDay = new javax.swing.JSpinner();
        lbName = new javax.swing.JLabel();
        lbInformation = new javax.swing.JLabel();
        lbTelephoneNumber = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        pfConfirmPassword = new javax.swing.JPasswordField();
        pfPassword = new javax.swing.JPasswordField();
        tfName = new javax.swing.JTextField();
        tfPhoneNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbId.setText("Número de cédula:");

        lbMail.setText("Correo");

        lbPasword.setText("Contraseña:");

        lbConfirmPassword.setText("Confirmar contraseña:");

        lbBornDate.setText("Fecha de nacimiento:");

        spYear.setModel(new javax.swing.SpinnerNumberModel(2000, 1924, 2005, 1));

        cbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        spDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        lbName.setText("Nombre:");

        lbInformation.setText("Ingrese sus datos por favor:");

        lbTelephoneNumber.setText("Número de telefono:");

        btRegister.setText("Registrarse");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        pfConfirmPassword.setPreferredSize(new java.awt.Dimension(95, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPasword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfId)
                            .addComponent(tfEmail)
                            .addComponent(pfPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbTelephoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbBornDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pfConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfName)
                            .addComponent(tfPhoneNumber))))
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btRegister)
                .addGap(57, 57, 57)
                .addComponent(btCancel)
                .addGap(0, 135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lbInformation)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMail)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPasword)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbConfirmPassword)
                    .addComponent(pfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBornDate)
                    .addComponent(spDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelephoneNumber)
                    .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRegister)
                    .addComponent(btCancel))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        // TODO add your handling code here:
        final String START_MESSAGE = "<html><p>";
        final String END_MESSAGE = "</p></html>";
        String message = "";
        if (checkMail()) {
            this.email = tfEmail.getText();
        } else {
            message += "Error en el correo electronico</p><p>";
        }
        
        if (!checkBornDate()) {
            message += "No cumple con los requisitos de edad</p><p>";
        }
        String tempPass = checkPassword();
        if (tempPass != null) {
            password = tempPass;
        } else {
            message += "La contraseña no es igual o no cumple con los requisitos</p><p>";
        }
        
        if (!message.isEmpty()) {
            MessageDialog errorRegistration = new MessageDialog(null, true, START_MESSAGE + message + END_MESSAGE, null);
        } else {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        }
        
    }//GEN-LAST:event_btRegisterActionPerformed

    private boolean checkId() {
        return false;
    }
    
    private boolean checkMail() {
        final String EMAIL_PATTERN = "[a-zA-Z0-9_.]{1,}[@]{1}[a-z1-9-.]+[.]{1}[a-z]{2,4}";
        Pattern pat = Pattern.compile(EMAIL_PATTERN);
        Matcher mat = pat.matcher(tfEmail.getText());
        if (!mat.matches()) {
            return false;
        }
        return true;
    }
    
    private boolean checkBornDate() {
        final byte MIN_AGE = 18;
        bornDate = new GregorianCalendar();
        bornDate.set((int) spYear.getValue(), cbMonth.getSelectedIndex() + 1, (int) spDay.getValue());
        String temp = new SimpleDateFormat("yyy-MM-dd").format(bornDate.getTime());
        LocalDate bornDateLocal = LocalDate.parse(temp);
        Period age = Period.between(bornDateLocal, LocalDate.now());
        if (age.getYears() >= MIN_AGE) {
            return true;
        }
        return false;
    }
    
    private boolean checkName() {
        return false;
    }
    
    private String checkPassword() {
        char[] pass1 = pfPassword.getPassword();
        char[] pass2 = pfConfirmPassword.getPassword();
        final String PASSWORD_PATTERN = "[[[a-z]{0,}|[A-Z]{0,}]+&[0-9]+]{8,}";
        String temp = "";
        if (pass1.length == pass2.length) {
            for (int i = 0; i < pass1.length; i++) {
                if (pass1[i] != pass2[i]) {
                    return null;
                }
                temp += pass1[i];
            }
            Pattern pat = Pattern.compile(PASSWORD_PATTERN);
            Matcher mat = pat.matcher(temp);
            if (mat.matches()) {
                System.out.println("cumple");
                return temp;
            }
        }
        return null;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterForm dialog = new RegisterForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void configureDate() {
        spYear.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                GregorianCalendar temp = new GregorianCalendar();
                temp.set(GregorianCalendar.YEAR, (int) spYear.getValue());
                if (temp.isLeapYear(temp.get(GregorianCalendar.YEAR))) {
                    leapYear = true;
                } else {
                    leapYear = false;
                }
            }
        });
        cbMonth.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                final byte JANUARY = 0;
                final byte FEBRUARY = 1;
                final byte MARCH = 2;
                final byte APRIL = 3;
                final byte MAY = 4;
                final byte JUNE = 5;
                final byte JULY = 6;
                final byte AUGUST = 7;
                final byte SEPTEMBER = 8;
                final byte OCTOBER = 9;
                final byte NOVEMBER = 10;
                final byte DECEMBER = 11;
                
                final byte LONG_MONTH = 31;
                final byte NORMAL_MONTH = 30;
                final byte FEBRUARY_LEAP = 29;
                final byte FEBRUARY_NORMAL = 28;
                
                SpinnerNumberModel model = new SpinnerNumberModel();
                model.setMinimum(Integer.valueOf(1));
                model.setStepSize(Integer.valueOf(1));
                model.setValue(spDay.getValue());
                switch (cbMonth.getSelectedIndex()) {
                    case FEBRUARY:
                        if (leapYear) {
                            model.setMaximum(Integer.valueOf(FEBRUARY_LEAP));
                        } else {
                            model.setMaximum(Integer.valueOf(FEBRUARY_NORMAL));
                        }
                        break;
                    case APRIL:
                    case JUNE:
                    case SEPTEMBER:
                    case NOVEMBER:
                        model.setMaximum(Integer.valueOf(NORMAL_MONTH));
                        break;
                    case JANUARY:
                    case MAY:
                    case MARCH:
                    case JULY:
                    case AUGUST:
                    case OCTOBER:
                    case DECEMBER:
                        model.setMaximum(Integer.valueOf(LONG_MONTH));
                        break;
                }
                spDay.setModel(model);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btRegister;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JLabel lbBornDate;
    private javax.swing.JLabel lbConfirmPassword;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbInformation;
    private javax.swing.JLabel lbMail;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPasword;
    private javax.swing.JLabel lbTelephoneNumber;
    private javax.swing.JPasswordField pfConfirmPassword;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JSpinner spDay;
    private javax.swing.JSpinner spYear;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
