
package server.view;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import server.model.AdminSessionComparator;
import server.model.Data;
import server.model.Server;
import server.model.Session;
import server.model.SessionListModel;
import server.model.User;
import server.model.UserListModel;

/**
 *
 * @author Joshua Mora Garita
 */
public class AdminView extends javax.swing.JFrame {

    /**
     * Probando pull Creates new form AdminView
     */
    private SessionListModel sessionModel;
    private UserListModel userModel;
    private static Data data;
    private static Server server;

    public AdminView(javax.swing.JFrame parent, boolean modal, Data data, Server server) {
        views();
        initComponents();
        setLocationRelativeTo(null);
        jListArea.setVisible(false);
        btnDeleteSession.setVisible(false);
        btnModify.setVisible(false);
        btnSessionDetails.setVisible(false);
        this.data = data;
        this.server = server;
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreateSession = new javax.swing.JButton();
        btnManageSessions = new javax.swing.JButton();
        btnShowSessions = new javax.swing.JButton();
        btnShowUsersList = new javax.swing.JButton();
        btnDeleteSession = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnSessionDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArea = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ModoAdmin.jpeg"))); // NOI18N

        btnCreateSession.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreateSession.setText("Crear Nueva Sesion");
        btnCreateSession.setBorder(null);
        btnCreateSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSessionActionPerformed(evt);
            }
        });

        btnManageSessions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManageSessions.setText("Administrar Sesiones");
        btnManageSessions.setBorder(null);
        btnManageSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSessionsActionPerformed(evt);
            }
        });

        btnShowSessions.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowSessions.setText("Lista de sesiones");
        btnShowSessions.setToolTipText("");
        btnShowSessions.setBorder(null);
        btnShowSessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSessionsActionPerformed(evt);
            }
        });

        btnShowUsersList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowUsersList.setText("Lista de usuarios");
        btnShowUsersList.setBorder(null);
        btnShowUsersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowUsersListActionPerformed(evt);
            }
        });

        btnDeleteSession.setText("Eliminar");
        btnDeleteSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSessionActionPerformed(evt);
            }
        });

        btnModify.setText("Modificar");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnSessionDetails.setText("Ver Sesion");
        btnSessionDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSessionDetailsActionPerformed(evt);
            }
        });

        jListArea.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnShowSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateSession, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteSession, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnSessionDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnManageSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnCreateSession, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                        .addComponent(btnShowSessions, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btnShowUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteSession, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSessionDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
    private void btnCreateSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSessionActionPerformed
        CreateSessions sessions = new CreateSessions(this, true, data);

        sessions.setVisible(true);

    }//GEN-LAST:event_btnCreateSessionActionPerformed

    private void btnManageSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSessionsActionPerformed

        sessionModel = new SessionListModel();
        jListArea.setModel(sessionModel);
        jListArea.setModel(sessionModel);
        jListArea.setVisible(true);
       
        int cont = 0;
        ArrayList<Session> arraySessions = new ArrayList<>();
        for (HashMap.Entry<String, Session> session : data.getSessions().entrySet()) {

            arraySessions.add(session.getValue());

        }
        arraySessions.sort(new AdminSessionComparator());

        for (int i = 0; i < arraySessions.size(); i++) {
            sessionModel.addSession(arraySessions.get(i));
        }

        btnDeleteSession.setVisible(true);
        btnModify.setVisible(true);
        btnSessionDetails.setVisible(false);


    }//GEN-LAST:event_btnManageSessionsActionPerformed

    private void btnShowSessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSessionsActionPerformed

        sessionModel = new SessionListModel();
        jListArea.setModel(sessionModel);
        jListArea.setVisible(true);
        jListArea.setAutoscrolls(true);

        ArrayList<Session> arraySessions = new ArrayList<>();
        for (HashMap.Entry<String, Session> session : data.getSessions().entrySet()) {

            arraySessions.add(session.getValue());

        }
        arraySessions.sort(new AdminSessionComparator());

        for (int i = 0; i < arraySessions.size(); i++) {
            sessionModel.addSession(arraySessions.get(i));
        }
        btnDeleteSession.setVisible(false);
        btnModify.setVisible(false);
        btnSessionDetails.setVisible(true);

    }//GEN-LAST:event_btnShowSessionsActionPerformed

    private void btnShowUsersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowUsersListActionPerformed
        userModel = new UserListModel();
        jListArea.setModel(userModel);
        jListArea.setVisible(true);
        for (HashMap.Entry<String, User> user : data.getUsers().entrySet()) {
            userModel.addUser(user.getValue());
        }
        btnDeleteSession.setVisible(false);
        btnModify.setVisible(false);
        btnSessionDetails.setVisible(false);
    }//GEN-LAST:event_btnShowUsersListActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        int index = -2;
        index = jListArea.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado una sesion o no hay sesiones en la lista", "Error", NORMAL);
            return;
        }
        if (index == -2) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna sesion", "Error", NORMAL);
            return;
        }
        Session session = sessionModel.getSession(index);

        ManageSessions manageSessions = new ManageSessions(this, true, data, session);

        manageSessions.setVisible(true);

        server.sendNotification(manageSessions.getMessage(), session);

    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSessionActionPerformed
        int index = -2;
        index = jListArea.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado una sesion o no hay sesiones en la lista", "Error", NORMAL);
            return;
        }
        if (index == -2) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna sesion", "Error", NORMAL);
            return;
        }
        data.deleteSession(sessionModel.getSession(index).getSesionId());
        sessionModel.deleteSession(index);

    }//GEN-LAST:event_btnDeleteSessionActionPerformed

    private void btnSessionDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSessionDetailsActionPerformed
        int index = -2;
        index = jListArea.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado una sesion o no hay sesiones en la lista", "Error", NORMAL);
            return;
        }
        if (index == -2) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna sesion", "Error", NORMAL);
            return;
        }
        Session session = sessionModel.getSession(index);

        SessionDetail sessionDetail = new SessionDetail(this, true, data, session);
        sessionDetail.setVisible(true);
    }//GEN-LAST:event_btnSessionDetailsActionPerformed

    private void views() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateSessions.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateSessions.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateSessions.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateSessions.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateSession;
    private javax.swing.JButton btnDeleteSession;
    private javax.swing.JButton btnManageSessions;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSessionDetails;
    private javax.swing.JButton btnShowSessions;
    private javax.swing.JButton btnShowUsersList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
